### ISSUE TITLE
Allow for modifying an existing schematic in memory

### ISSUE THREAD

**Issue by jivid** [manifold-lang/manifold-core#49]
For some of the microfluidics backend work I'm doing, I need to add attributes to the serialized version of a circuit once the schematic has already been generated. After talking to @mtrberzi today, I don't think there's a way to do this currently.

**Comment by mtrberzi** [comment]
The problem that we need to solve is that a `Schematic`, as well as all of its components, is immutable once it has been created (or deserialized). What we would like is some kind of object that takes a "base" `Schematic` and then applies a sequence of modifications to it in order to create a fresh `Schematic`.

**Comment by mtrberzi** [comment]
An alternative solution is to modify the serialized form of the `Schematic`, essentially making all the changes at the same time, and then deserializing it to get the new copy. This is easier to implement, but it is less safe since we cannot verify that the edits leave the `Schematic` in a consistent state until we deserialize it.

**Comment by mtrberzi** [comment]
Okay, this is finally ready for review.
